[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
nixpkgs = "python311"

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
